-- ============================================
-- SPK Akreditasi AHP - Seed Matriks Perbandingan Alternatif per Sub-Kriteria
-- 22 Sub-Kriteria x 14 Alternatif (upper triangle only, diagonal auto = 1)
-- Urutan alternatif: A1=TeknikMesin, A2=TeknikIndustri, A3=RekayasaLogistik,
--   A4=TekMatMet, A5=TekKimia, A6=RekKeselamatan, A7=TekPerkapalan,
--   A8=TekKelautan, A9=TekLingkungan, A10=TekSipil, A11=TekElektro,
--   A12=TekBiomedis, A13=TransportasiLaut, A14=SistemPerkapalan
-- ============================================

-- Clear existing alternative comparison data
DELETE FROM alternative_comparisons;

-- Helper: We use sub_criteria.id lookup via code
-- Format: (sub_criteria_id, row_id, col_id, value)

-- ============================================
-- SC1.1 – Kekhasan VMTS
-- ============================================
INSERT INTO alternative_comparisons (sub_criteria_id, alternative_row_id, alternative_col_id, value) VALUES
-- A1 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A2'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A3'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A4'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A5'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A6'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A7'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A8'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A9'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A12'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
-- A2 vs others (from row A2 upper)
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A3'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A4'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A5'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A6'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A7'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A8'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A9'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A12'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
-- A3 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A4'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A5'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A6'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A7'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A8'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A9'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A10'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A11'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A12'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
-- A4 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A5'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A6'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A7'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A8'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A9'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A12'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
-- A5 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A6'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A7'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A8'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A9'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A10'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A11'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A12'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
-- A6 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A7'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A8'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A9'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A10'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A11'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A12'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
-- A7 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A8'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A9'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A10'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A11'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A12'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A13'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A14'),2.0),
-- A8 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A9'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A10'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A11'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A12'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
-- A9 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A10'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A11'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A12'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A13'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A14'),2.0),
-- A10 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A12'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
-- A11 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A12'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
-- A12 vs others
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A13'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A14'),1.0),
-- A13 vs A14
((SELECT id FROM sub_criteria WHERE code='SC1.1'),(SELECT id FROM alternatives WHERE code='A13'),(SELECT id FROM alternatives WHERE code='A14'),1.0);

-- ============================================
-- SC1.2 – Mekanisme Penyusunan VMTS
-- ============================================
INSERT INTO alternative_comparisons (sub_criteria_id, alternative_row_id, alternative_col_id, value) VALUES
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A2'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A3'),0.645),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A4'),0.541),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A5'),0.465),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A6'),0.408),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A7'),0.365),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A8'),0.333),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A9'),0.31),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A10'),0.465),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A11'),0.541),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A12'),0.645),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A13'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A14'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A3'),0.806),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A4'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A5'),0.558),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A6'),0.49),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A7'),0.438),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A8'),0.4),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A9'),0.372),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A10'),0.558),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A11'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A12'),0.806),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A13'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A14'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A4'),0.827),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A5'),0.692),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A6'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A7'),0.536),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A8'),0.49),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A9'),0.455),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A10'),0.692),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A11'),0.827),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A12'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A13'),1.24),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A14'),1.55),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A5'),0.836),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A6'),0.726),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A7'),0.65),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A8'),0.594),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A9'),0.556),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A10'),0.836),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A12'),1.209),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A14'),1.85),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A6'),0.875),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A7'),0.782),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A8'),0.714),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A9'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A11'),1.195),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A12'),1.445),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A13'),1.792),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A14'),2.15),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A7'),0.889),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A8'),0.81),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A9'),0.76),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A10'),1.143),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A11'),1.377),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A12'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A13'),2.041),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A14'),2.45),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A8'),0.92),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A9'),0.87),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A10'),1.278),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A11'),1.54),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A12'),1.865),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A13'),2.283),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A14'),2.74),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A9'),0.95),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A10'),1.4),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A11'),1.683),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A12'),2.041),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A14'),3.0),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A10'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A11'),1.8),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A12'),2.198),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A13'),2.688),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A14'),3.22),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A11'),1.195),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A12'),1.445),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A13'),1.792),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A14'),2.15),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A12'),1.209),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A14'),1.85),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A13'),1.24),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A14'),1.55),
((SELECT id FROM sub_criteria WHERE code='SC1.2'),(SELECT id FROM alternatives WHERE code='A13'),(SELECT id FROM alternatives WHERE code='A14'),1.25);

-- ============================================
-- SC1.3 – Tingkat Pemahaman & Pencapaian VMTS
-- ============================================
INSERT INTO alternative_comparisons (sub_criteria_id, alternative_row_id, alternative_col_id, value) VALUES
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A2'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A3'),0.4),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A4'),0.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A5'),0.286),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A6'),0.25),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A7'),0.222),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A8'),0.2),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A9'),0.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A10'),0.4),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A11'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A12'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A13'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A3'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A4'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A5'),0.571),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A6'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A7'),0.444),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A8'),0.4),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A9'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A10'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A12'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A4'),0.833),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A5'),0.714),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A6'),0.625),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A7'),0.556),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A8'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A9'),0.833),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A11'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A12'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A13'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A5'),0.857),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A6'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A7'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A8'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A9'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A10'),1.2),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A11'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A12'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A13'),3.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A6'),0.875),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A7'),0.778),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A8'),0.7),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A9'),1.167),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A10'),1.4),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A11'),1.75),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A12'),2.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A13'),3.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A7'),0.889),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A8'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A9'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A10'),1.6),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A11'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A12'),2.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A13'),4.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A14'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A8'),0.9),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A9'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A10'),1.8),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A11'),2.25),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A12'),3.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A13'),4.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A14'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A9'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A10'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A11'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A12'),3.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A13'),5.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A14'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A10'),1.2),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A11'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A12'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A13'),3.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A11'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A12'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A13'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A12'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A13'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A14'),2.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A14'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC1.3'),(SELECT id FROM alternatives WHERE code='A13'),(SELECT id FROM alternatives WHERE code='A14'),1.0);

-- ============================================
-- SC2.1 – Sistem Tata Pamong
-- ============================================
INSERT INTO alternative_comparisons (sub_criteria_id, alternative_row_id, alternative_col_id, value) VALUES
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A2'),0.833),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A3'),0.714),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A4'),0.625),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A5'),0.556),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A6'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A7'),0.455),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A8'),0.417),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A9'),0.385),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A10'),0.556),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A11'),0.625),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A12'),0.714),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A13'),0.833),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A1'),(SELECT id FROM alternatives WHERE code='A14'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A3'),0.857),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A4'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A5'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A6'),0.6),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A7'),0.545),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A8'),0.5),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A9'),0.462),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A10'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A11'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A12'),0.857),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A13'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A2'),(SELECT id FROM alternatives WHERE code='A14'),1.2),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A4'),0.875),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A5'),0.778),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A6'),0.7),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A7'),0.636),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A8'),0.583),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A9'),0.538),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A10'),0.778),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A11'),0.875),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A12'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A13'),1.167),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A3'),(SELECT id FROM alternatives WHERE code='A14'),1.4),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A5'),0.889),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A6'),0.8),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A7'),0.727),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A8'),0.667),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A9'),0.615),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A10'),0.889),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A11'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A12'),1.143),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A13'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A4'),(SELECT id FROM alternatives WHERE code='A14'),1.6),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A6'),0.9),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A7'),0.818),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A8'),0.75),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A9'),0.692),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A10'),1.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A11'),1.125),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A12'),1.286),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A5'),(SELECT id FROM alternatives WHERE code='A14'),1.8),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A7'),0.909),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A8'),0.833),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A9'),0.769),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A10'),1.111),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A11'),1.25),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A12'),1.429),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A13'),1.667),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A6'),(SELECT id FROM alternatives WHERE code='A14'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A8'),0.917),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A9'),0.846),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A10'),1.222),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A11'),1.375),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A12'),1.571),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A13'),1.833),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A7'),(SELECT id FROM alternatives WHERE code='A14'),2.2),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A9'),0.923),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A10'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A11'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A12'),1.714),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A13'),2.0),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A8'),(SELECT id FROM alternatives WHERE code='A14'),2.4),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A10'),1.444),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A11'),1.625),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A12'),1.857),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A13'),2.167),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A9'),(SELECT id FROM alternatives WHERE code='A14'),2.6),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A11'),1.125),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A12'),1.286),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A13'),1.5),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A10'),(SELECT id FROM alternatives WHERE code='A14'),1.8),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A12'),1.143),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A13'),1.333),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A11'),(SELECT id FROM alternatives WHERE code='A14'),1.6),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A13'),1.167),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A12'),(SELECT id FROM alternatives WHERE code='A14'),1.4),
((SELECT id FROM sub_criteria WHERE code='SC2.1'),(SELECT id FROM alternatives WHERE code='A13'),(SELECT id FROM alternatives WHERE code='A14'),1.2);

-- NOTE: SC2.2 through SC5.5 follow the same pattern.
-- Due to size, the remaining 18 sub-criteria seed data is in seed_alt_comparisons_part2.sql
